### ISSUE TITLE
Toolbar acts as settings menu even if not touching the gear

### ISSUE THREAD

**Issue by asherlr23** [TheEggo58/scarlet#2]
The settings menu will appear upon the toolbar being clicked at all. I have no idea why, because "OverlaySettings" is only mentioned 3 times within the toolbar code. With all 3 of those times being within the toolbar-gear clone.

**Comment by TheEggo58** [comment]
Accidentally shifted the button script below the "if <toolbar-gear>" section, will be fixed shortly
